from django.urls import path

from . import views

urlpatterns = [
    path("", views.landing_view, name="landing"),
    path("app/", views.index_view, name="index"),
    path("offline/", views.offline_view, name="offline"),
    path("sw.js", views.service_worker_view, name="service-worker"),
    path("id", views.client_id_metadata_view, name="client-id-metadata"),
    path("login/", views.login_view, name="login"),
    path("login/callback/", views.callback_view, name="callback"),
    path("logout/", views.logout_view, name="logout"),
    path("settings/", views.settings_view, name="settings"),
    path("channel/<path:channel_uid>/", views.timeline_view, name="timeline"),
    path("api/mark-read/", views.mark_read_view, name="mark-read"),
    path("api/mark-unread/", views.mark_unread_view, name="mark-unread"),
    path("api/timeline/remove/", views.remove_entry_view, name="timeline-remove"),
    path("api/channels/create/", views.channel_create_view, name="channel-create"),
    path("api/channels/mark-read/", views.channel_mark_read_view, name="channel-mark-read"),
    path("api/channels/rename/", views.channel_rename_view, name="channel-rename"),
    path("api/channels/delete/", views.channel_delete_view, name="channel-delete"),
    path("api/channels/order/", views.channel_order_view, name="channel-order"),
    path("api/feeds/search/", views.feed_search_view, name="feed-search"),
    path("api/feeds/preview/", views.feed_preview_view, name="feed-preview"),
    path("api/feeds/list/<path:channel_uid>/", views.feed_list_view, name="feed-list"),
    path("api/feeds/follow/", views.feed_follow_view, name="feed-follow"),
    path("api/feeds/unfollow/", views.feed_unfollow_view, name="feed-unfollow"),
    path("api/mute/", views.mute_user_view, name="mute-user"),
    path("api/unmute/", views.unmute_user_view, name="unmute-user"),
    path("api/block/", views.block_user_view, name="block-user"),
    path("new/", views.new_post_view, name="new-post"),
    path("drafts/save/", views.draft_save_view, name="draft-save"),
    path("drafts/<int:draft_id>/delete/", views.draft_delete_view, name="draft-delete"),
    path("opml/export/", views.opml_export_view, name="opml-export"),
    path("opml/import/", views.opml_import_view, name="opml-import"),
    path("account/export/", views.account_export_view, name="account-export"),
    path("account/delete/", views.account_delete_view, name="account-delete"),
    path("api/image/convert/", views.convert_image_view, name="image-convert"),
    path("api/micropub/media/", views.upload_media_view, name="micropub-media"),
    path("api/micropub/like/", views.micropub_like_view, name="micropub-like"),
    path("api/micropub/repost/", views.micropub_repost_view, name="micropub-repost"),
    path("api/micropub/reply/", views.micropub_reply_view, name="micropub-reply"),
    path("discover/", views.discover_view, name="discover"),
    path("admin/", views.admin_view, name="admin"),
    path("admin/broadcasts/create/", views.broadcast_create_view, name="broadcast-create"),
    path("admin/broadcasts/<int:broadcast_id>/toggle/", views.broadcast_toggle_view, name="broadcast-toggle"),
    path("api/broadcast/<int:broadcast_id>/dismiss/", views.broadcast_dismiss_view, name="broadcast-dismiss"),
    path("api/broadcasts/", views.broadcast_banner_view, name="broadcast-banner"),
]
