# Generated by Django 6.0.2 on 2026-02-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('author_url', models.URLField(blank=True, default='', max_length=2048)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url', models.URLField(db_index=True, max_length=2048)),
                ('kind', models.CharField(choices=[('like', 'Like'), ('reply', 'Reply'), ('repost', 'Repost')], max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('result_url', models.URLField(blank=True, default='', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='microsub_client.cachedentry')),
            ],
            options={
                'unique_together': {('user_url', 'entry', 'kind')},
            },
        ),
    ]
