# Generated by Django 6.0.2 on 2026-02-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsub_client', '0002_broadcast_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('photo', models.URLField(blank=True, default='', max_length=2048)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_login'],
            },
        ),
    ]
