# Generated by Django 6.0.2 on 2026-02-17 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsub_client', '0003_knownuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url', models.URLField(max_length=2048, unique=True)),
                ('default_filter', models.CharField(default='all', max_length=10)),
                ('mark_read_behavior', models.CharField(choices=[('explicit', 'Explicit'), ('interaction', 'Interaction'), ('scroll_past', 'Scroll Past')], default='explicit', max_length=20)),
                ('expand_content', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DismissedBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url', models.URLField(db_index=True, max_length=2048)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microsub_client.broadcast')),
            ],
            options={
                'unique_together': {('user_url', 'broadcast')},
            },
        ),
    ]
