# Generated by Django 6.0.2 on 2026-02-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsub_client', '0005_usersettings_infinite_scroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_gardn_harvest',
            field=models.BooleanField(default=False),
        ),
    ]
