# Generated by Django 6.0.2 on 2026-02-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsub_client', '0006_add_show_gardn_harvest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url', models.URLField(db_index=True, max_length=2048)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('content', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
                ('photos', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
