# Generated by Django 6.0.8 on 2026-08-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsub_client', '0008_normalize_user_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='show_gardn_harvest',
        ),
    ]
